### ISSUE TITLE
i filled username and password  still error

### ISSUE THREAD

**Issue by abelamm** [BOT-HAT/Smm-Job-Bot#7]
Traceback (most recent call last):
  File "F:\Smm-Job-Bot-main\Smm-Job-Bot-main\smmbot.py", line 55, in <module>
    key=login()
  File "F:\Smm-Job-Bot-main\Smm-Job-Bot-main\smmbot.py", line 19, in login
    apiresp = json.loads(apiresp)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by KneesDev** [comment]
You can obviously see that the username and password is not the issue. The code itself is problematic.
